package com.Dao.entity;
// Generated May 7, 2017 2:26:51 AM by Hibernate Tools 3.6.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Allocation generated by hbm2java
 */
public class Allocation implements java.io.Serializable {

	private Integer allocationId;
	private Repository repository;
	private int allocationStockNo;
	private Integer allocationIsOccupied;
	private Integer allocationStocktype;
	private Integer allocationStocknum;
	private Integer allocationStockid;
	private Set<MaterialStockmanage> materialStockmanages = new HashSet<MaterialStockmanage>(0);
	private Set<WipStockmanage> wipStockmanages = new HashSet<WipStockmanage>(0);
	private Set<OtsStockmanage> otsStockmanages = new HashSet<OtsStockmanage>(0);

	public Allocation() {
	}

	public Allocation(Repository repository, int allocationStockNo) {
		this.repository = repository;
		this.allocationStockNo = allocationStockNo;
	}

	public Allocation(Repository repository, int allocationStockNo, Integer allocationIsOccupied,
			Integer allocationStocktype, Integer allocationStocknum, Integer allocationStockid,
			Set<MaterialStockmanage> materialStockmanages, Set<WipStockmanage> wipStockmanages,
			Set<OtsStockmanage> otsStockmanages) {
		this.repository = repository;
		this.allocationStockNo = allocationStockNo;
		this.allocationIsOccupied = allocationIsOccupied;
		this.allocationStocktype = allocationStocktype;
		this.allocationStocknum = allocationStocknum;
		this.allocationStockid = allocationStockid;
		this.materialStockmanages = materialStockmanages;
		this.wipStockmanages = wipStockmanages;
		this.otsStockmanages = otsStockmanages;
	}

	public Integer getAllocationId() {
		return this.allocationId;
	}

	public void setAllocationId(Integer allocationId) {
		this.allocationId = allocationId;
	}

	public Repository getRepository() {
		return this.repository;
	}

	public void setRepository(Repository repository) {
		this.repository = repository;
	}

	public int getAllocationStockNo() {
		return this.allocationStockNo;
	}

	public void setAllocationStockNo(int allocationStockNo) {
		this.allocationStockNo = allocationStockNo;
	}

	public Integer getAllocationIsOccupied() {
		return this.allocationIsOccupied;
	}

	public void setAllocationIsOccupied(Integer allocationIsOccupied) {
		this.allocationIsOccupied = allocationIsOccupied;
	}

	public Integer getAllocationStocktype() {
		return this.allocationStocktype;
	}

	public void setAllocationStocktype(Integer allocationStocktype) {
		this.allocationStocktype = allocationStocktype;
	}

	public Integer getAllocationStocknum() {
		return this.allocationStocknum;
	}

	public void setAllocationStocknum(Integer allocationStocknum) {
		this.allocationStocknum = allocationStocknum;
	}

	public Integer getAllocationStockid() {
		return this.allocationStockid;
	}

	public void setAllocationStockid(Integer allocationStockid) {
		this.allocationStockid = allocationStockid;
	}

	public Set<MaterialStockmanage> getMaterialStockmanages() {
		return this.materialStockmanages;
	}

	public void setMaterialStockmanages(Set<MaterialStockmanage> materialStockmanages) {
		this.materialStockmanages = materialStockmanages;
	}

	public Set<WipStockmanage> getWipStockmanages() {
		return this.wipStockmanages;
	}

	public void setWipStockmanages(Set<WipStockmanage> wipStockmanages) {
		this.wipStockmanages = wipStockmanages;
	}

	public Set<OtsStockmanage> getOtsStockmanages() {
		return this.otsStockmanages;
	}

	public void setOtsStockmanages(Set<OtsStockmanage> otsStockmanages) {
		this.otsStockmanages = otsStockmanages;
	}

}
