package com.Dao.entity;
// Generated May 7, 2017 2:26:51 AM by Hibernate Tools 3.6.0.Final

/**
 * CategoryId generated by hbm2java
 */
public class CategoryId implements java.io.Serializable {

	private int categoryId;
	private String categoryName;

	public CategoryId() {
	}

	public CategoryId(int categoryId, String categoryName) {
		this.categoryId = categoryId;
		this.categoryName = categoryName;
	}

	public int getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(int categoryId) {
		this.categoryId = categoryId;
	}

	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CategoryId))
			return false;
		CategoryId castOther = (CategoryId) other;

		return (this.getCategoryId() == castOther.getCategoryId())
				&& ((this.getCategoryName() == castOther.getCategoryName())
						|| (this.getCategoryName() != null && castOther.getCategoryName() != null
								&& this.getCategoryName().equals(castOther.getCategoryName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCategoryId();
		result = 37 * result + (getCategoryName() == null ? 0 : this.getCategoryName().hashCode());
		return result;
	}

}
