package com.Dao.entity;
// Generated May 7, 2017 2:26:51 AM by Hibernate Tools 3.6.0.Final

/**
 * MaterialsstoreId generated by hbm2java
 */
public class MaterialsstoreId implements java.io.Serializable {

	private int materialsStoreRepositoryId;
	private int materialsStoreMaterialsId;

	public MaterialsstoreId() {
	}

	public MaterialsstoreId(int materialsStoreRepositoryId, int materialsStoreMaterialsId) {
		this.materialsStoreRepositoryId = materialsStoreRepositoryId;
		this.materialsStoreMaterialsId = materialsStoreMaterialsId;
	}

	public int getMaterialsStoreRepositoryId() {
		return this.materialsStoreRepositoryId;
	}

	public void setMaterialsStoreRepositoryId(int materialsStoreRepositoryId) {
		this.materialsStoreRepositoryId = materialsStoreRepositoryId;
	}

	public int getMaterialsStoreMaterialsId() {
		return this.materialsStoreMaterialsId;
	}

	public void setMaterialsStoreMaterialsId(int materialsStoreMaterialsId) {
		this.materialsStoreMaterialsId = materialsStoreMaterialsId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MaterialsstoreId))
			return false;
		MaterialsstoreId castOther = (MaterialsstoreId) other;

		return (this.getMaterialsStoreRepositoryId() == castOther.getMaterialsStoreRepositoryId())
				&& (this.getMaterialsStoreMaterialsId() == castOther.getMaterialsStoreMaterialsId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMaterialsStoreRepositoryId();
		result = 37 * result + this.getMaterialsStoreMaterialsId();
		return result;
	}

}
