package com.Dao.entity;
// Generated May 7, 2017 2:26:51 AM by Hibernate Tools 3.6.0.Final

import java.util.Date;

/**
 * MaterialGet generated by hbm2java
 */
public class MaterialGet implements java.io.Serializable {

	private Integer materialsGetId;
	private Materials materials;
	private Repository repository;
	private Station station;
	private Date stationGetMaterialsTime;
	private Integer stationGetMaterialsAmount;
	private Integer stationGetMaterialsStatus;

	public MaterialGet() {
	}

	public MaterialGet(Materials materials, Station station) {
		this.materials = materials;
		this.station = station;
	}

	public MaterialGet(Materials materials, Repository repository, Station station, Date stationGetMaterialsTime,
			Integer stationGetMaterialsAmount, Integer stationGetMaterialsStatus) {
		this.materials = materials;
		this.repository = repository;
		this.station = station;
		this.stationGetMaterialsTime = stationGetMaterialsTime;
		this.stationGetMaterialsAmount = stationGetMaterialsAmount;
		this.stationGetMaterialsStatus = stationGetMaterialsStatus;
	}

	public Integer getMaterialsGetId() {
		return this.materialsGetId;
	}

	public void setMaterialsGetId(Integer materialsGetId) {
		this.materialsGetId = materialsGetId;
	}

	public Materials getMaterials() {
		return this.materials;
	}

	public void setMaterials(Materials materials) {
		this.materials = materials;
	}

	public Repository getRepository() {
		return this.repository;
	}

	public void setRepository(Repository repository) {
		this.repository = repository;
	}

	public Station getStation() {
		return this.station;
	}

	public void setStation(Station station) {
		this.station = station;
	}

	public Date getStationGetMaterialsTime() {
		return this.stationGetMaterialsTime;
	}

	public void setStationGetMaterialsTime(Date stationGetMaterialsTime) {
		this.stationGetMaterialsTime = stationGetMaterialsTime;
	}

	public Integer getStationGetMaterialsAmount() {
		return this.stationGetMaterialsAmount;
	}

	public void setStationGetMaterialsAmount(Integer stationGetMaterialsAmount) {
		this.stationGetMaterialsAmount = stationGetMaterialsAmount;
	}

	public Integer getStationGetMaterialsStatus() {
		return this.stationGetMaterialsStatus;
	}

	public void setStationGetMaterialsStatus(Integer stationGetMaterialsStatus) {
		this.stationGetMaterialsStatus = stationGetMaterialsStatus;
	}

}
