package com.Dao.entity;
// Generated May 7, 2017 2:26:51 AM by Hibernate Tools 3.6.0.Final

/**
 * MaterialsWip generated by hbm2java
 */
public class MaterialsWip implements java.io.Serializable {

	private MaterialsWipId id;
	private Materials materials;
	private Wip wip;
	private Integer materialNum;

	public MaterialsWip() {
	}

	public MaterialsWip(MaterialsWipId id, Materials materials, Wip wip) {
		this.id = id;
		this.materials = materials;
		this.wip = wip;
	}

	public MaterialsWip(MaterialsWipId id, Materials materials, Wip wip, Integer materialNum) {
		this.id = id;
		this.materials = materials;
		this.wip = wip;
		this.materialNum = materialNum;
	}

	public MaterialsWipId getId() {
		return this.id;
	}

	public void setId(MaterialsWipId id) {
		this.id = id;
	}

	public Materials getMaterials() {
		return this.materials;
	}

	public void setMaterials(Materials materials) {
		this.materials = materials;
	}

	public Wip getWip() {
		return this.wip;
	}

	public void setWip(Wip wip) {
		this.wip = wip;
	}

	public Integer getMaterialNum() {
		return this.materialNum;
	}

	public void setMaterialNum(Integer materialNum) {
		this.materialNum = materialNum;
	}

}
