package com.Dao.entity;
// Generated May 7, 2017 2:26:51 AM by Hibernate Tools 3.6.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Materials generated by hbm2java
 */
public class Materials implements java.io.Serializable {

	private Integer materialsId;
	private String materialsName;
	private String materialsNotes;
	private Integer materialsMinPur;
	private Short materialsIsLack;
	private Integer materialsRemains;
	private Integer materialsAllowed;
	private Set<MaterialGet> materialGets = new HashSet<MaterialGet>(0);
	private Set<MaterialsWip> materialsWips = new HashSet<MaterialsWip>(0);
	private Set<Purchaseorder> purchaseorders = new HashSet<Purchaseorder>(0);
	private Set<ProvidematerialPeriod> providematerialPeriods = new HashSet<ProvidematerialPeriod>(0);
	private Set<MaterialStockmanage> materialStockmanages = new HashSet<MaterialStockmanage>(0);
	private Set<Materialsstore> materialsstores = new HashSet<Materialsstore>(0);

	public Materials() {
	}

	public Materials(String materialsName) {
		this.materialsName = materialsName;
	}

	public Materials(String materialsName, String materialsNotes, Integer materialsMinPur, Short materialsIsLack,
			Integer materialsRemains, Integer materialsAllowed, Set<MaterialGet> materialGets,
			Set<MaterialsWip> materialsWips, Set<Purchaseorder> purchaseorders,
			Set<ProvidematerialPeriod> providematerialPeriods, Set<MaterialStockmanage> materialStockmanages,
			Set<Materialsstore> materialsstores) {
		this.materialsName = materialsName;
		this.materialsNotes = materialsNotes;
		this.materialsMinPur = materialsMinPur;
		this.materialsIsLack = materialsIsLack;
		this.materialsRemains = materialsRemains;
		this.materialsAllowed = materialsAllowed;
		this.materialGets = materialGets;
		this.materialsWips = materialsWips;
		this.purchaseorders = purchaseorders;
		this.providematerialPeriods = providematerialPeriods;
		this.materialStockmanages = materialStockmanages;
		this.materialsstores = materialsstores;
	}

	public Integer getMaterialsId() {
		return this.materialsId;
	}

	public void setMaterialsId(Integer materialsId) {
		this.materialsId = materialsId;
	}

	public String getMaterialsName() {
		return this.materialsName;
	}

	public void setMaterialsName(String materialsName) {
		this.materialsName = materialsName;
	}

	public String getMaterialsNotes() {
		return this.materialsNotes;
	}

	public void setMaterialsNotes(String materialsNotes) {
		this.materialsNotes = materialsNotes;
	}

	public Integer getMaterialsMinPur() {
		return this.materialsMinPur;
	}

	public void setMaterialsMinPur(Integer materialsMinPur) {
		this.materialsMinPur = materialsMinPur;
	}

	public Short getMaterialsIsLack() {
		return this.materialsIsLack;
	}

	public void setMaterialsIsLack(Short materialsIsLack) {
		this.materialsIsLack = materialsIsLack;
	}

	public Integer getMaterialsRemains() {
		return this.materialsRemains;
	}

	public void setMaterialsRemains(Integer materialsRemains) {
		this.materialsRemains = materialsRemains;
	}

	public Integer getMaterialsAllowed() {
		return this.materialsAllowed;
	}

	public void setMaterialsAllowed(Integer materialsAllowed) {
		this.materialsAllowed = materialsAllowed;
	}

	public Set<MaterialGet> getMaterialGets() {
		return this.materialGets;
	}

	public void setMaterialGets(Set<MaterialGet> materialGets) {
		this.materialGets = materialGets;
	}

	public Set<MaterialsWip> getMaterialsWips() {
		return this.materialsWips;
	}

	public void setMaterialsWips(Set<MaterialsWip> materialsWips) {
		this.materialsWips = materialsWips;
	}

	public Set<Purchaseorder> getPurchaseorders() {
		return this.purchaseorders;
	}

	public void setPurchaseorders(Set<Purchaseorder> purchaseorders) {
		this.purchaseorders = purchaseorders;
	}

	public Set<ProvidematerialPeriod> getProvidematerialPeriods() {
		return this.providematerialPeriods;
	}

	public void setProvidematerialPeriods(Set<ProvidematerialPeriod> providematerialPeriods) {
		this.providematerialPeriods = providematerialPeriods;
	}

	public Set<MaterialStockmanage> getMaterialStockmanages() {
		return this.materialStockmanages;
	}

	public void setMaterialStockmanages(Set<MaterialStockmanage> materialStockmanages) {
		this.materialStockmanages = materialStockmanages;
	}

	public Set<Materialsstore> getMaterialsstores() {
		return this.materialsstores;
	}

	public void setMaterialsstores(Set<Materialsstore> materialsstores) {
		this.materialsstores = materialsstores;
	}

}
