package com.Dao.entity;
// Generated May 7, 2017 2:26:51 AM by Hibernate Tools 3.6.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Order generated by hbm2java
 */
public class Order implements java.io.Serializable {

	private Integer orderId;
	private Date orderBeginTime;
	private Date orderEndTime;
	private int orderDealPersonId;
	private Long orderTotalPrice;
	private int orderStatus;
	private String orderNotes;
	private String orderBuyer;
	private String orderBuyerContact;
	private String orderBuyerRepresantName;
	private Set<Virtualotsstore> virtualotsstores = new HashSet<Virtualotsstore>(0);
	private Set<Productsell> productsells = new HashSet<Productsell>(0);
	private Set<Virtualwipstore> virtualwipstores = new HashSet<Virtualwipstore>(0);

	public Order() {
	}

	public Order(Date orderBeginTime, int orderDealPersonId, int orderStatus, String orderBuyer,
			String orderBuyerContact, String orderBuyerRepresantName) {
		this.orderBeginTime = orderBeginTime;
		this.orderDealPersonId = orderDealPersonId;
		this.orderStatus = orderStatus;
		this.orderBuyer = orderBuyer;
		this.orderBuyerContact = orderBuyerContact;
		this.orderBuyerRepresantName = orderBuyerRepresantName;
	}

	public Order(Date orderBeginTime, Date orderEndTime, int orderDealPersonId, Long orderTotalPrice, int orderStatus,
			String orderNotes, String orderBuyer, String orderBuyerContact, String orderBuyerRepresantName,
			Set<Virtualotsstore> virtualotsstores, Set<Productsell> productsells,
			Set<Virtualwipstore> virtualwipstores) {
		this.orderBeginTime = orderBeginTime;
		this.orderEndTime = orderEndTime;
		this.orderDealPersonId = orderDealPersonId;
		this.orderTotalPrice = orderTotalPrice;
		this.orderStatus = orderStatus;
		this.orderNotes = orderNotes;
		this.orderBuyer = orderBuyer;
		this.orderBuyerContact = orderBuyerContact;
		this.orderBuyerRepresantName = orderBuyerRepresantName;
		this.virtualotsstores = virtualotsstores;
		this.productsells = productsells;
		this.virtualwipstores = virtualwipstores;
	}

	public Integer getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	public Date getOrderBeginTime() {
		return this.orderBeginTime;
	}

	public void setOrderBeginTime(Date orderBeginTime) {
		this.orderBeginTime = orderBeginTime;
	}

	public Date getOrderEndTime() {
		return this.orderEndTime;
	}

	public void setOrderEndTime(Date orderEndTime) {
		this.orderEndTime = orderEndTime;
	}

	public int getOrderDealPersonId() {
		return this.orderDealPersonId;
	}

	public void setOrderDealPersonId(int orderDealPersonId) {
		this.orderDealPersonId = orderDealPersonId;
	}

	public Long getOrderTotalPrice() {
		return this.orderTotalPrice;
	}

	public void setOrderTotalPrice(Long orderTotalPrice) {
		this.orderTotalPrice = orderTotalPrice;
	}

	public int getOrderStatus() {
		return this.orderStatus;
	}

	public void setOrderStatus(int orderStatus) {
		this.orderStatus = orderStatus;
	}

	public String getOrderNotes() {
		return this.orderNotes;
	}

	public void setOrderNotes(String orderNotes) {
		this.orderNotes = orderNotes;
	}

	public String getOrderBuyer() {
		return this.orderBuyer;
	}

	public void setOrderBuyer(String orderBuyer) {
		this.orderBuyer = orderBuyer;
	}

	public String getOrderBuyerContact() {
		return this.orderBuyerContact;
	}

	public void setOrderBuyerContact(String orderBuyerContact) {
		this.orderBuyerContact = orderBuyerContact;
	}

	public String getOrderBuyerRepresantName() {
		return this.orderBuyerRepresantName;
	}

	public void setOrderBuyerRepresantName(String orderBuyerRepresantName) {
		this.orderBuyerRepresantName = orderBuyerRepresantName;
	}

	public Set<Virtualotsstore> getVirtualotsstores() {
		return this.virtualotsstores;
	}

	public void setVirtualotsstores(Set<Virtualotsstore> virtualotsstores) {
		this.virtualotsstores = virtualotsstores;
	}

	public Set<Productsell> getProductsells() {
		return this.productsells;
	}

	public void setProductsells(Set<Productsell> productsells) {
		this.productsells = productsells;
	}

	public Set<Virtualwipstore> getVirtualwipstores() {
		return this.virtualwipstores;
	}

	public void setVirtualwipstores(Set<Virtualwipstore> virtualwipstores) {
		this.virtualwipstores = virtualwipstores;
	}

}
