package com.Dao.entity;
// Generated May 7, 2017 2:26:51 AM by Hibernate Tools 3.6.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Ots generated by hbm2java
 */
public class Ots implements java.io.Serializable {

	private Integer otsId;
	private Category category;
	private String ostName;
	private String ostNotes;
	private int ostRemains;
	private int ostAllowed;
	private short ostIsLack;
	private Set<Productsell> productsells = new HashSet<Productsell>(0);
	private Set<Virtualotsstore> virtualotsstores = new HashSet<Virtualotsstore>(0);
	private Set<Category> categories = new HashSet<Category>(0);
	private Set<Otsstore> otsstores = new HashSet<Otsstore>(0);
	private Set<WipOts> wipOtses = new HashSet<WipOts>(0);
	private Set<OtsStockmanage> otsStockmanages = new HashSet<OtsStockmanage>(0);

	public Ots() {
	}

	public Ots(String ostName, int ostRemains, int ostAllowed, short ostIsLack) {
		this.ostName = ostName;
		this.ostRemains = ostRemains;
		this.ostAllowed = ostAllowed;
		this.ostIsLack = ostIsLack;
	}

	public Ots(Category category, String ostName, String ostNotes, int ostRemains, int ostAllowed, short ostIsLack,
			Set<Productsell> productsells, Set<Virtualotsstore> virtualotsstores, Set<Category> categories,
			Set<Otsstore> otsstores, Set<WipOts> wipOtses, Set<OtsStockmanage> otsStockmanages) {
		this.category = category;
		this.ostName = ostName;
		this.ostNotes = ostNotes;
		this.ostRemains = ostRemains;
		this.ostAllowed = ostAllowed;
		this.ostIsLack = ostIsLack;
		this.productsells = productsells;
		this.virtualotsstores = virtualotsstores;
		this.categories = categories;
		this.otsstores = otsstores;
		this.wipOtses = wipOtses;
		this.otsStockmanages = otsStockmanages;
	}

	public Integer getOtsId() {
		return this.otsId;
	}

	public void setOtsId(Integer otsId) {
		this.otsId = otsId;
	}

	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	public String getOstName() {
		return this.ostName;
	}

	public void setOstName(String ostName) {
		this.ostName = ostName;
	}

	public String getOstNotes() {
		return this.ostNotes;
	}

	public void setOstNotes(String ostNotes) {
		this.ostNotes = ostNotes;
	}

	public int getOstRemains() {
		return this.ostRemains;
	}

	public void setOstRemains(int ostRemains) {
		this.ostRemains = ostRemains;
	}

	public int getOstAllowed() {
		return this.ostAllowed;
	}

	public void setOstAllowed(int ostAllowed) {
		this.ostAllowed = ostAllowed;
	}

	public short getOstIsLack() {
		return this.ostIsLack;
	}

	public void setOstIsLack(short ostIsLack) {
		this.ostIsLack = ostIsLack;
	}

	public Set<Productsell> getProductsells() {
		return this.productsells;
	}

	public void setProductsells(Set<Productsell> productsells) {
		this.productsells = productsells;
	}

	public Set<Virtualotsstore> getVirtualotsstores() {
		return this.virtualotsstores;
	}

	public void setVirtualotsstores(Set<Virtualotsstore> virtualotsstores) {
		this.virtualotsstores = virtualotsstores;
	}

	public Set<Category> getCategories() {
		return this.categories;
	}

	public void setCategories(Set<Category> categories) {
		this.categories = categories;
	}

	public Set<Otsstore> getOtsstores() {
		return this.otsstores;
	}

	public void setOtsstores(Set<Otsstore> otsstores) {
		this.otsstores = otsstores;
	}

	public Set<WipOts> getWipOtses() {
		return this.wipOtses;
	}

	public void setWipOtses(Set<WipOts> wipOtses) {
		this.wipOtses = wipOtses;
	}

	public Set<OtsStockmanage> getOtsStockmanages() {
		return this.otsStockmanages;
	}

	public void setOtsStockmanages(Set<OtsStockmanage> otsStockmanages) {
		this.otsStockmanages = otsStockmanages;
	}

}
