package com.Dao.entity;
// Generated May 7, 2017 2:26:51 AM by Hibernate Tools 3.6.0.Final

/**
 * Otsstore generated by hbm2java
 */
public class Otsstore implements java.io.Serializable {

	private OtsstoreId id;
	private Repository repository;
	private Ots ots;
	private Integer otsStoreOtsNum;

	public Otsstore() {
	}

	public Otsstore(OtsstoreId id, Repository repository, Ots ots) {
		this.id = id;
		this.repository = repository;
		this.ots = ots;
	}

	public Otsstore(OtsstoreId id, Repository repository, Ots ots, Integer otsStoreOtsNum) {
		this.id = id;
		this.repository = repository;
		this.ots = ots;
		this.otsStoreOtsNum = otsStoreOtsNum;
	}

	public OtsstoreId getId() {
		return this.id;
	}

	public void setId(OtsstoreId id) {
		this.id = id;
	}

	public Repository getRepository() {
		return this.repository;
	}

	public void setRepository(Repository repository) {
		this.repository = repository;
	}

	public Ots getOts() {
		return this.ots;
	}

	public void setOts(Ots ots) {
		this.ots = ots;
	}

	public Integer getOtsStoreOtsNum() {
		return this.otsStoreOtsNum;
	}

	public void setOtsStoreOtsNum(Integer otsStoreOtsNum) {
		this.otsStoreOtsNum = otsStoreOtsNum;
	}

}
