package com.Dao.entity;
// Generated May 7, 2017 2:26:51 AM by Hibernate Tools 3.6.0.Final

/**
 * OtsstoreId generated by hbm2java
 */
public class OtsstoreId implements java.io.Serializable {

	private int otsStoreRepositoryId;
	private int otsStoreOtsId;

	public OtsstoreId() {
	}

	public OtsstoreId(int otsStoreRepositoryId, int otsStoreOtsId) {
		this.otsStoreRepositoryId = otsStoreRepositoryId;
		this.otsStoreOtsId = otsStoreOtsId;
	}

	public int getOtsStoreRepositoryId() {
		return this.otsStoreRepositoryId;
	}

	public void setOtsStoreRepositoryId(int otsStoreRepositoryId) {
		this.otsStoreRepositoryId = otsStoreRepositoryId;
	}

	public int getOtsStoreOtsId() {
		return this.otsStoreOtsId;
	}

	public void setOtsStoreOtsId(int otsStoreOtsId) {
		this.otsStoreOtsId = otsStoreOtsId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OtsstoreId))
			return false;
		OtsstoreId castOther = (OtsstoreId) other;

		return (this.getOtsStoreRepositoryId() == castOther.getOtsStoreRepositoryId())
				&& (this.getOtsStoreOtsId() == castOther.getOtsStoreOtsId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getOtsStoreRepositoryId();
		result = 37 * result + this.getOtsStoreOtsId();
		return result;
	}

}
