package com.Dao.entity;
// Generated May 7, 2017 2:26:51 AM by Hibernate Tools 3.6.0.Final

import java.util.Date;

/**
 * OtsStockmanage generated by hbm2java
 */
public class OtsStockmanage implements java.io.Serializable {

	private String otsStockmanageId;
	private Ots ots;
	private Allocation allocation;
	private Staff staff;
	private Repository repository;
	private Integer otsAmount;
	private Integer otsTakeOtsPersonId;
	private Integer otsBringOtsPersonId;
	private Integer otsStockManageType;
	private Date otsDate;

	public OtsStockmanage() {
	}

	public OtsStockmanage(String otsStockmanageId, Ots ots, Allocation allocation) {
		this.otsStockmanageId = otsStockmanageId;
		this.ots = ots;
		this.allocation = allocation;
	}

	public OtsStockmanage(String otsStockmanageId, Ots ots, Allocation allocation, Staff staff, Repository repository,
			Integer otsAmount, Integer otsTakeOtsPersonId, Integer otsBringOtsPersonId, Integer otsStockManageType,
			Date otsDate) {
		this.otsStockmanageId = otsStockmanageId;
		this.ots = ots;
		this.allocation = allocation;
		this.staff = staff;
		this.repository = repository;
		this.otsAmount = otsAmount;
		this.otsTakeOtsPersonId = otsTakeOtsPersonId;
		this.otsBringOtsPersonId = otsBringOtsPersonId;
		this.otsStockManageType = otsStockManageType;
		this.otsDate = otsDate;
	}

	public String getOtsStockmanageId() {
		return this.otsStockmanageId;
	}

	public void setOtsStockmanageId(String otsStockmanageId) {
		this.otsStockmanageId = otsStockmanageId;
	}

	public Ots getOts() {
		return this.ots;
	}

	public void setOts(Ots ots) {
		this.ots = ots;
	}

	public Allocation getAllocation() {
		return this.allocation;
	}

	public void setAllocation(Allocation allocation) {
		this.allocation = allocation;
	}

	public Staff getStaff() {
		return this.staff;
	}

	public void setStaff(Staff staff) {
		this.staff = staff;
	}

	public Repository getRepository() {
		return this.repository;
	}

	public void setRepository(Repository repository) {
		this.repository = repository;
	}

	public Integer getOtsAmount() {
		return this.otsAmount;
	}

	public void setOtsAmount(Integer otsAmount) {
		this.otsAmount = otsAmount;
	}

	public Integer getOtsTakeOtsPersonId() {
		return this.otsTakeOtsPersonId;
	}

	public void setOtsTakeOtsPersonId(Integer otsTakeOtsPersonId) {
		this.otsTakeOtsPersonId = otsTakeOtsPersonId;
	}

	public Integer getOtsBringOtsPersonId() {
		return this.otsBringOtsPersonId;
	}

	public void setOtsBringOtsPersonId(Integer otsBringOtsPersonId) {
		this.otsBringOtsPersonId = otsBringOtsPersonId;
	}

	public Integer getOtsStockManageType() {
		return this.otsStockManageType;
	}

	public void setOtsStockManageType(Integer otsStockManageType) {
		this.otsStockManageType = otsStockManageType;
	}

	public Date getOtsDate() {
		return this.otsDate;
	}

	public void setOtsDate(Date otsDate) {
		this.otsDate = otsDate;
	}

}
