package com.Dao.entity;
// Generated May 7, 2017 2:26:51 AM by Hibernate Tools 3.6.0.Final

/**
 * Productsell generated by hbm2java
 */
public class Productsell implements java.io.Serializable {

	private ProductsellId id;
	private Ots ots;
	private Order order;
	private Integer productSellAmount;

	public Productsell() {
	}

	public Productsell(ProductsellId id, Ots ots, Order order) {
		this.id = id;
		this.ots = ots;
		this.order = order;
	}

	public Productsell(ProductsellId id, Ots ots, Order order, Integer productSellAmount) {
		this.id = id;
		this.ots = ots;
		this.order = order;
		this.productSellAmount = productSellAmount;
	}

	public ProductsellId getId() {
		return this.id;
	}

	public void setId(ProductsellId id) {
		this.id = id;
	}

	public Ots getOts() {
		return this.ots;
	}

	public void setOts(Ots ots) {
		this.ots = ots;
	}

	public Order getOrder() {
		return this.order;
	}

	public void setOrder(Order order) {
		this.order = order;
	}

	public Integer getProductSellAmount() {
		return this.productSellAmount;
	}

	public void setProductSellAmount(Integer productSellAmount) {
		this.productSellAmount = productSellAmount;
	}

}
