package com.Dao.entity;
// Generated May 7, 2017 2:26:51 AM by Hibernate Tools 3.6.0.Final

/**
 * ProductsellId generated by hbm2java
 */
public class ProductsellId implements java.io.Serializable {

	private int otsId;
	private int orderId;

	public ProductsellId() {
	}

	public ProductsellId(int otsId, int orderId) {
		this.otsId = otsId;
		this.orderId = orderId;
	}

	public int getOtsId() {
		return this.otsId;
	}

	public void setOtsId(int otsId) {
		this.otsId = otsId;
	}

	public int getOrderId() {
		return this.orderId;
	}

	public void setOrderId(int orderId) {
		this.orderId = orderId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProductsellId))
			return false;
		ProductsellId castOther = (ProductsellId) other;

		return (this.getOtsId() == castOther.getOtsId()) && (this.getOrderId() == castOther.getOrderId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getOtsId();
		result = 37 * result + this.getOrderId();
		return result;
	}

}
