package com.Dao.entity;
// Generated May 7, 2017 2:26:51 AM by Hibernate Tools 3.6.0.Final

/**
 * ProvidematerialPeriodId generated by hbm2java
 */
public class ProvidematerialPeriodId implements java.io.Serializable {

	private int providerId;
	private int materialsId;

	public ProvidematerialPeriodId() {
	}

	public ProvidematerialPeriodId(int providerId, int materialsId) {
		this.providerId = providerId;
		this.materialsId = materialsId;
	}

	public int getProviderId() {
		return this.providerId;
	}

	public void setProviderId(int providerId) {
		this.providerId = providerId;
	}

	public int getMaterialsId() {
		return this.materialsId;
	}

	public void setMaterialsId(int materialsId) {
		this.materialsId = materialsId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProvidematerialPeriodId))
			return false;
		ProvidematerialPeriodId castOther = (ProvidematerialPeriodId) other;

		return (this.getProviderId() == castOther.getProviderId())
				&& (this.getMaterialsId() == castOther.getMaterialsId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getProviderId();
		result = 37 * result + this.getMaterialsId();
		return result;
	}

}
