package com.Dao.entity;
// Generated May 7, 2017 2:26:51 AM by Hibernate Tools 3.6.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Repository generated by hbm2java
 */
public class Repository implements java.io.Serializable {

	private Integer repositoryId;
	private String repositoryAddress;
	private Integer repositoryManageId;
	private Set<OtsStockmanage> otsStockmanages = new HashSet<OtsStockmanage>(0);
	private Set<Virtualotsstore> virtualotsstores = new HashSet<Virtualotsstore>(0);
	private Set<MaterialGet> materialGets = new HashSet<MaterialGet>(0);
	private Set<Storelog> storelogs = new HashSet<Storelog>(0);
	private Set<WipGet> wipGets = new HashSet<WipGet>(0);
	private Set<Allocation> allocations = new HashSet<Allocation>(0);
	private Set<Otsstore> otsstores = new HashSet<Otsstore>(0);
	private Set<WipStockmanage> wipStockmanages = new HashSet<WipStockmanage>(0);
	private Set<Virtualwipstore> virtualwipstores = new HashSet<Virtualwipstore>(0);
	private Set<Materialsstore> materialsstores = new HashSet<Materialsstore>(0);
	private Set<Wipstore> wipstores = new HashSet<Wipstore>(0);
	private Set<MaterialStockmanage> materialStockmanages = new HashSet<MaterialStockmanage>(0);

	public Repository() {
	}

	public Repository(String repositoryAddress) {
		this.repositoryAddress = repositoryAddress;
	}

	public Repository(String repositoryAddress, Integer repositoryManageId, Set<OtsStockmanage> otsStockmanages,
			Set<Virtualotsstore> virtualotsstores, Set<MaterialGet> materialGets, Set<Storelog> storelogs,
			Set<WipGet> wipGets, Set<Allocation> allocations, Set<Otsstore> otsstores,
			Set<WipStockmanage> wipStockmanages, Set<Virtualwipstore> virtualwipstores,
			Set<Materialsstore> materialsstores, Set<Wipstore> wipstores,
			Set<MaterialStockmanage> materialStockmanages) {
		this.repositoryAddress = repositoryAddress;
		this.repositoryManageId = repositoryManageId;
		this.otsStockmanages = otsStockmanages;
		this.virtualotsstores = virtualotsstores;
		this.materialGets = materialGets;
		this.storelogs = storelogs;
		this.wipGets = wipGets;
		this.allocations = allocations;
		this.otsstores = otsstores;
		this.wipStockmanages = wipStockmanages;
		this.virtualwipstores = virtualwipstores;
		this.materialsstores = materialsstores;
		this.wipstores = wipstores;
		this.materialStockmanages = materialStockmanages;
	}

	public Integer getRepositoryId() {
		return this.repositoryId;
	}

	public void setRepositoryId(Integer repositoryId) {
		this.repositoryId = repositoryId;
	}

	public String getRepositoryAddress() {
		return this.repositoryAddress;
	}

	public void setRepositoryAddress(String repositoryAddress) {
		this.repositoryAddress = repositoryAddress;
	}

	public Integer getRepositoryManageId() {
		return this.repositoryManageId;
	}

	public void setRepositoryManageId(Integer repositoryManageId) {
		this.repositoryManageId = repositoryManageId;
	}

	public Set<OtsStockmanage> getOtsStockmanages() {
		return this.otsStockmanages;
	}

	public void setOtsStockmanages(Set<OtsStockmanage> otsStockmanages) {
		this.otsStockmanages = otsStockmanages;
	}

	public Set<Virtualotsstore> getVirtualotsstores() {
		return this.virtualotsstores;
	}

	public void setVirtualotsstores(Set<Virtualotsstore> virtualotsstores) {
		this.virtualotsstores = virtualotsstores;
	}

	public Set<MaterialGet> getMaterialGets() {
		return this.materialGets;
	}

	public void setMaterialGets(Set<MaterialGet> materialGets) {
		this.materialGets = materialGets;
	}

	public Set<Storelog> getStorelogs() {
		return this.storelogs;
	}

	public void setStorelogs(Set<Storelog> storelogs) {
		this.storelogs = storelogs;
	}

	public Set<WipGet> getWipGets() {
		return this.wipGets;
	}

	public void setWipGets(Set<WipGet> wipGets) {
		this.wipGets = wipGets;
	}

	public Set<Allocation> getAllocations() {
		return this.allocations;
	}

	public void setAllocations(Set<Allocation> allocations) {
		this.allocations = allocations;
	}

	public Set<Otsstore> getOtsstores() {
		return this.otsstores;
	}

	public void setOtsstores(Set<Otsstore> otsstores) {
		this.otsstores = otsstores;
	}

	public Set<WipStockmanage> getWipStockmanages() {
		return this.wipStockmanages;
	}

	public void setWipStockmanages(Set<WipStockmanage> wipStockmanages) {
		this.wipStockmanages = wipStockmanages;
	}

	public Set<Virtualwipstore> getVirtualwipstores() {
		return this.virtualwipstores;
	}

	public void setVirtualwipstores(Set<Virtualwipstore> virtualwipstores) {
		this.virtualwipstores = virtualwipstores;
	}

	public Set<Materialsstore> getMaterialsstores() {
		return this.materialsstores;
	}

	public void setMaterialsstores(Set<Materialsstore> materialsstores) {
		this.materialsstores = materialsstores;
	}

	public Set<Wipstore> getWipstores() {
		return this.wipstores;
	}

	public void setWipstores(Set<Wipstore> wipstores) {
		this.wipstores = wipstores;
	}

	public Set<MaterialStockmanage> getMaterialStockmanages() {
		return this.materialStockmanages;
	}

	public void setMaterialStockmanages(Set<MaterialStockmanage> materialStockmanages) {
		this.materialStockmanages = materialStockmanages;
	}

}
