package com.Dao.entity;
// Generated May 7, 2017 2:26:51 AM by Hibernate Tools 3.6.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Staff generated by hbm2java
 */
public class Staff implements java.io.Serializable {

	private Integer staffId;
	private Department department;
	private Station station;
	private String staffName;
	private String staffGender;
	private String staffTitle;
	private String staffContact;
	private int staffPriority;
	private Set<Storelog> storelogs = new HashSet<Storelog>(0);
	private Set<MaterialStockmanage> materialStockmanages = new HashSet<MaterialStockmanage>(0);
	private Set<OtsStockmanage> otsStockmanages = new HashSet<OtsStockmanage>(0);

	public Staff() {
	}

	public Staff(String staffName, String staffTitle, String staffContact, int staffPriority) {
		this.staffName = staffName;
		this.staffTitle = staffTitle;
		this.staffContact = staffContact;
		this.staffPriority = staffPriority;
	}

	public Staff(Department department, Station station, String staffName, String staffGender, String staffTitle,
			String staffContact, int staffPriority, Set<Storelog> storelogs,
			Set<MaterialStockmanage> materialStockmanages, Set<OtsStockmanage> otsStockmanages) {
		this.department = department;
		this.station = station;
		this.staffName = staffName;
		this.staffGender = staffGender;
		this.staffTitle = staffTitle;
		this.staffContact = staffContact;
		this.staffPriority = staffPriority;
		this.storelogs = storelogs;
		this.materialStockmanages = materialStockmanages;
		this.otsStockmanages = otsStockmanages;
	}

	public Integer getStaffId() {
		return this.staffId;
	}

	public void setStaffId(Integer staffId) {
		this.staffId = staffId;
	}

	public Department getDepartment() {
		return this.department;
	}

	public void setDepartment(Department department) {
		this.department = department;
	}

	public Station getStation() {
		return this.station;
	}

	public void setStation(Station station) {
		this.station = station;
	}

	public String getStaffName() {
		return this.staffName;
	}

	public void setStaffName(String staffName) {
		this.staffName = staffName;
	}

	public String getStaffGender() {
		return this.staffGender;
	}

	public void setStaffGender(String staffGender) {
		this.staffGender = staffGender;
	}

	public String getStaffTitle() {
		return this.staffTitle;
	}

	public void setStaffTitle(String staffTitle) {
		this.staffTitle = staffTitle;
	}

	public String getStaffContact() {
		return this.staffContact;
	}

	public void setStaffContact(String staffContact) {
		this.staffContact = staffContact;
	}

	public int getStaffPriority() {
		return this.staffPriority;
	}

	public void setStaffPriority(int staffPriority) {
		this.staffPriority = staffPriority;
	}

	public Set<Storelog> getStorelogs() {
		return this.storelogs;
	}

	public void setStorelogs(Set<Storelog> storelogs) {
		this.storelogs = storelogs;
	}

	public Set<MaterialStockmanage> getMaterialStockmanages() {
		return this.materialStockmanages;
	}

	public void setMaterialStockmanages(Set<MaterialStockmanage> materialStockmanages) {
		this.materialStockmanages = materialStockmanages;
	}

	public Set<OtsStockmanage> getOtsStockmanages() {
		return this.otsStockmanages;
	}

	public void setOtsStockmanages(Set<OtsStockmanage> otsStockmanages) {
		this.otsStockmanages = otsStockmanages;
	}

}
