package com.Dao.entity;
// Generated May 7, 2017 2:26:51 AM by Hibernate Tools 3.6.0.Final

/**
 * StaffStation generated by hbm2java
 */
public class StaffStation implements java.io.Serializable {

	private int staffId;
	private int stationId;

	public StaffStation() {
	}

	public StaffStation(int staffId, int stationId) {
		this.staffId = staffId;
		this.stationId = stationId;
	}

	public int getStaffId() {
		return this.staffId;
	}

	public void setStaffId(int staffId) {
		this.staffId = staffId;
	}

	public int getStationId() {
		return this.stationId;
	}

	public void setStationId(int stationId) {
		this.stationId = stationId;
	}

}
