package com.Dao.entity;
// Generated May 7, 2017 2:26:51 AM by Hibernate Tools 3.6.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Station generated by hbm2java
 */
public class Station implements java.io.Serializable {

	private Integer stationId;
	private String stationName;
	private Set<Staff> staffs = new HashSet<Staff>(0);
	private Set<MaterialGet> materialGets = new HashSet<MaterialGet>(0);
	private Set<WipGet> wipGets = new HashSet<WipGet>(0);

	public Station() {
	}

	public Station(String stationName) {
		this.stationName = stationName;
	}

	public Station(String stationName, Set<Staff> staffs, Set<MaterialGet> materialGets, Set<WipGet> wipGets) {
		this.stationName = stationName;
		this.staffs = staffs;
		this.materialGets = materialGets;
		this.wipGets = wipGets;
	}

	public Integer getStationId() {
		return this.stationId;
	}

	public void setStationId(Integer stationId) {
		this.stationId = stationId;
	}

	public String getStationName() {
		return this.stationName;
	}

	public void setStationName(String stationName) {
		this.stationName = stationName;
	}

	public Set<Staff> getStaffs() {
		return this.staffs;
	}

	public void setStaffs(Set<Staff> staffs) {
		this.staffs = staffs;
	}

	public Set<MaterialGet> getMaterialGets() {
		return this.materialGets;
	}

	public void setMaterialGets(Set<MaterialGet> materialGets) {
		this.materialGets = materialGets;
	}

	public Set<WipGet> getWipGets() {
		return this.wipGets;
	}

	public void setWipGets(Set<WipGet> wipGets) {
		this.wipGets = wipGets;
	}

}
