package com.Dao.entity;
// Generated May 7, 2017 2:26:51 AM by Hibernate Tools 3.6.0.Final

import java.util.Date;

/**
 * Storelog generated by hbm2java
 */
public class Storelog implements java.io.Serializable {

	private Integer logId;
	private Repository repository;
	private Staff staff;
	private Integer logAmount;
	private Integer logStockManageType;
	private Integer logType;
	private Date logDate;
	private String logOrderid;

	public Storelog() {
	}

	public Storelog(Repository repository, Staff staff, Integer logAmount, Integer logStockManageType, Integer logType,
			Date logDate, String logOrderid) {
		this.repository = repository;
		this.staff = staff;
		this.logAmount = logAmount;
		this.logStockManageType = logStockManageType;
		this.logType = logType;
		this.logDate = logDate;
		this.logOrderid = logOrderid;
	}

	public Integer getLogId() {
		return this.logId;
	}

	public void setLogId(Integer logId) {
		this.logId = logId;
	}

	public Repository getRepository() {
		return this.repository;
	}

	public void setRepository(Repository repository) {
		this.repository = repository;
	}

	public Staff getStaff() {
		return this.staff;
	}

	public void setStaff(Staff staff) {
		this.staff = staff;
	}

	public Integer getLogAmount() {
		return this.logAmount;
	}

	public void setLogAmount(Integer logAmount) {
		this.logAmount = logAmount;
	}

	public Integer getLogStockManageType() {
		return this.logStockManageType;
	}

	public void setLogStockManageType(Integer logStockManageType) {
		this.logStockManageType = logStockManageType;
	}

	public Integer getLogType() {
		return this.logType;
	}

	public void setLogType(Integer logType) {
		this.logType = logType;
	}

	public Date getLogDate() {
		return this.logDate;
	}

	public void setLogDate(Date logDate) {
		this.logDate = logDate;
	}

	public String getLogOrderid() {
		return this.logOrderid;
	}

	public void setLogOrderid(String logOrderid) {
		this.logOrderid = logOrderid;
	}

}
