package com.Dao.entity;
// Generated May 7, 2017 2:26:51 AM by Hibernate Tools 3.6.0.Final

/**
 * Virtualotsstore generated by hbm2java
 */
public class Virtualotsstore implements java.io.Serializable {

	private VirtualotsstoreId id;
	private Ots ots;
	private Order order;
	private Repository repository;
	private Integer virtualOtsStoreOtsNum;

	public Virtualotsstore() {
	}

	public Virtualotsstore(VirtualotsstoreId id, Ots ots, Order order, Repository repository) {
		this.id = id;
		this.ots = ots;
		this.order = order;
		this.repository = repository;
	}

	public Virtualotsstore(VirtualotsstoreId id, Ots ots, Order order, Repository repository,
			Integer virtualOtsStoreOtsNum) {
		this.id = id;
		this.ots = ots;
		this.order = order;
		this.repository = repository;
		this.virtualOtsStoreOtsNum = virtualOtsStoreOtsNum;
	}

	public VirtualotsstoreId getId() {
		return this.id;
	}

	public void setId(VirtualotsstoreId id) {
		this.id = id;
	}

	public Ots getOts() {
		return this.ots;
	}

	public void setOts(Ots ots) {
		this.ots = ots;
	}

	public Order getOrder() {
		return this.order;
	}

	public void setOrder(Order order) {
		this.order = order;
	}

	public Repository getRepository() {
		return this.repository;
	}

	public void setRepository(Repository repository) {
		this.repository = repository;
	}

	public Integer getVirtualOtsStoreOtsNum() {
		return this.virtualOtsStoreOtsNum;
	}

	public void setVirtualOtsStoreOtsNum(Integer virtualOtsStoreOtsNum) {
		this.virtualOtsStoreOtsNum = virtualOtsStoreOtsNum;
	}

}
