package com.Dao.entity;
// Generated May 7, 2017 2:26:51 AM by Hibernate Tools 3.6.0.Final

/**
 * VirtualmaterialsstoreId generated by hbm2java
 */
public class VirtualmaterialsstoreId implements java.io.Serializable {

	private int virtualMaterialsStoreRepositoryId;
	private int virtualMaterialsStoreMaterialsId;
	private int virtualMaterialsStoreOrderId;

	public VirtualmaterialsstoreId() {
	}

	public VirtualmaterialsstoreId(int virtualMaterialsStoreRepositoryId, int virtualMaterialsStoreMaterialsId,
			int virtualMaterialsStoreOrderId) {
		this.virtualMaterialsStoreRepositoryId = virtualMaterialsStoreRepositoryId;
		this.virtualMaterialsStoreMaterialsId = virtualMaterialsStoreMaterialsId;
		this.virtualMaterialsStoreOrderId = virtualMaterialsStoreOrderId;
	}

	public int getVirtualMaterialsStoreRepositoryId() {
		return this.virtualMaterialsStoreRepositoryId;
	}

	public void setVirtualMaterialsStoreRepositoryId(int virtualMaterialsStoreRepositoryId) {
		this.virtualMaterialsStoreRepositoryId = virtualMaterialsStoreRepositoryId;
	}

	public int getVirtualMaterialsStoreMaterialsId() {
		return this.virtualMaterialsStoreMaterialsId;
	}

	public void setVirtualMaterialsStoreMaterialsId(int virtualMaterialsStoreMaterialsId) {
		this.virtualMaterialsStoreMaterialsId = virtualMaterialsStoreMaterialsId;
	}

	public int getVirtualMaterialsStoreOrderId() {
		return this.virtualMaterialsStoreOrderId;
	}

	public void setVirtualMaterialsStoreOrderId(int virtualMaterialsStoreOrderId) {
		this.virtualMaterialsStoreOrderId = virtualMaterialsStoreOrderId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VirtualmaterialsstoreId))
			return false;
		VirtualmaterialsstoreId castOther = (VirtualmaterialsstoreId) other;

		return (this.getVirtualMaterialsStoreRepositoryId() == castOther.getVirtualMaterialsStoreRepositoryId())
				&& (this.getVirtualMaterialsStoreMaterialsId() == castOther.getVirtualMaterialsStoreMaterialsId())
				&& (this.getVirtualMaterialsStoreOrderId() == castOther.getVirtualMaterialsStoreOrderId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getVirtualMaterialsStoreRepositoryId();
		result = 37 * result + this.getVirtualMaterialsStoreMaterialsId();
		result = 37 * result + this.getVirtualMaterialsStoreOrderId();
		return result;
	}

}
