package com.Dao.entity;
// Generated May 7, 2017 2:26:51 AM by Hibernate Tools 3.6.0.Final

/**
 * Virtualwipstore generated by hbm2java
 */
public class Virtualwipstore implements java.io.Serializable {

	private VirtualwipstoreId id;
	private Order order;
	private Repository repository;
	private Wip wip;
	private int virtualWipStoreWipNum;

	public Virtualwipstore() {
	}

	public Virtualwipstore(VirtualwipstoreId id, Order order, Repository repository, Wip wip,
			int virtualWipStoreWipNum) {
		this.id = id;
		this.order = order;
		this.repository = repository;
		this.wip = wip;
		this.virtualWipStoreWipNum = virtualWipStoreWipNum;
	}

	public VirtualwipstoreId getId() {
		return this.id;
	}

	public void setId(VirtualwipstoreId id) {
		this.id = id;
	}

	public Order getOrder() {
		return this.order;
	}

	public void setOrder(Order order) {
		this.order = order;
	}

	public Repository getRepository() {
		return this.repository;
	}

	public void setRepository(Repository repository) {
		this.repository = repository;
	}

	public Wip getWip() {
		return this.wip;
	}

	public void setWip(Wip wip) {
		this.wip = wip;
	}

	public int getVirtualWipStoreWipNum() {
		return this.virtualWipStoreWipNum;
	}

	public void setVirtualWipStoreWipNum(int virtualWipStoreWipNum) {
		this.virtualWipStoreWipNum = virtualWipStoreWipNum;
	}

}
