package com.Dao.entity;
// Generated May 7, 2017 2:26:51 AM by Hibernate Tools 3.6.0.Final

/**
 * Virtualmaterialsstore generated by hbm2java
 */
public class Virtualmaterialsstore implements java.io.Serializable {

	private VirtualmaterialsstoreId id;
	private Integer virtualMaterialsStoreMaterialsNum;

	public Virtualmaterialsstore() {
	}

	public Virtualmaterialsstore(VirtualmaterialsstoreId id) {
		this.id = id;
	}

	public Virtualmaterialsstore(VirtualmaterialsstoreId id, Integer virtualMaterialsStoreMaterialsNum) {
		this.id = id;
		this.virtualMaterialsStoreMaterialsNum = virtualMaterialsStoreMaterialsNum;
	}

	public VirtualmaterialsstoreId getId() {
		return this.id;
	}

	public void setId(VirtualmaterialsstoreId id) {
		this.id = id;
	}

	public Integer getVirtualMaterialsStoreMaterialsNum() {
		return this.virtualMaterialsStoreMaterialsNum;
	}

	public void setVirtualMaterialsStoreMaterialsNum(Integer virtualMaterialsStoreMaterialsNum) {
		this.virtualMaterialsStoreMaterialsNum = virtualMaterialsStoreMaterialsNum;
	}

}
