package com.Dao.entity;
// Generated May 7, 2017 2:26:51 AM by Hibernate Tools 3.6.0.Final

/**
 * VirtualwipstoreId generated by hbm2java
 */
public class VirtualwipstoreId implements java.io.Serializable {

	private int virtualWipStoreRepositoryId;
	private int virtualWipStoreWipId;
	private int virtualWipStoreOrderId;

	public VirtualwipstoreId() {
	}

	public VirtualwipstoreId(int virtualWipStoreRepositoryId, int virtualWipStoreWipId, int virtualWipStoreOrderId) {
		this.virtualWipStoreRepositoryId = virtualWipStoreRepositoryId;
		this.virtualWipStoreWipId = virtualWipStoreWipId;
		this.virtualWipStoreOrderId = virtualWipStoreOrderId;
	}

	public int getVirtualWipStoreRepositoryId() {
		return this.virtualWipStoreRepositoryId;
	}

	public void setVirtualWipStoreRepositoryId(int virtualWipStoreRepositoryId) {
		this.virtualWipStoreRepositoryId = virtualWipStoreRepositoryId;
	}

	public int getVirtualWipStoreWipId() {
		return this.virtualWipStoreWipId;
	}

	public void setVirtualWipStoreWipId(int virtualWipStoreWipId) {
		this.virtualWipStoreWipId = virtualWipStoreWipId;
	}

	public int getVirtualWipStoreOrderId() {
		return this.virtualWipStoreOrderId;
	}

	public void setVirtualWipStoreOrderId(int virtualWipStoreOrderId) {
		this.virtualWipStoreOrderId = virtualWipStoreOrderId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VirtualwipstoreId))
			return false;
		VirtualwipstoreId castOther = (VirtualwipstoreId) other;

		return (this.getVirtualWipStoreRepositoryId() == castOther.getVirtualWipStoreRepositoryId())
				&& (this.getVirtualWipStoreWipId() == castOther.getVirtualWipStoreWipId())
				&& (this.getVirtualWipStoreOrderId() == castOther.getVirtualWipStoreOrderId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getVirtualWipStoreRepositoryId();
		result = 37 * result + this.getVirtualWipStoreWipId();
		result = 37 * result + this.getVirtualWipStoreOrderId();
		return result;
	}

}
