package com.Dao.entity;
// Generated May 7, 2017 2:26:51 AM by Hibernate Tools 3.6.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Wip generated by hbm2java
 */
public class Wip implements java.io.Serializable {

	private Integer wipId;
	private String wipName;
	private String wipNotes;
	private int wipRemains;
	private int wipAllowed;
	private short wipIsLack;
	private Set<WipGet> wipGets = new HashSet<WipGet>(0);
	private Set<WipStockmanage> wipStockmanages = new HashSet<WipStockmanage>(0);
	private Set<Virtualwipstore> virtualwipstores = new HashSet<Virtualwipstore>(0);
	private Set<WipOts> wipOtses = new HashSet<WipOts>(0);
	private Set<Wipstore> wipstores = new HashSet<Wipstore>(0);
	private Set<MaterialsWip> materialsWips = new HashSet<MaterialsWip>(0);

	public Wip() {
	}

	public Wip(String wipName, int wipRemains, int wipAllowed, short wipIsLack) {
		this.wipName = wipName;
		this.wipRemains = wipRemains;
		this.wipAllowed = wipAllowed;
		this.wipIsLack = wipIsLack;
	}

	public Wip(String wipName, String wipNotes, int wipRemains, int wipAllowed, short wipIsLack, Set<WipGet> wipGets,
			Set<WipStockmanage> wipStockmanages, Set<Virtualwipstore> virtualwipstores, Set<WipOts> wipOtses,
			Set<Wipstore> wipstores, Set<MaterialsWip> materialsWips) {
		this.wipName = wipName;
		this.wipNotes = wipNotes;
		this.wipRemains = wipRemains;
		this.wipAllowed = wipAllowed;
		this.wipIsLack = wipIsLack;
		this.wipGets = wipGets;
		this.wipStockmanages = wipStockmanages;
		this.virtualwipstores = virtualwipstores;
		this.wipOtses = wipOtses;
		this.wipstores = wipstores;
		this.materialsWips = materialsWips;
	}

	public Integer getWipId() {
		return this.wipId;
	}

	public void setWipId(Integer wipId) {
		this.wipId = wipId;
	}

	public String getWipName() {
		return this.wipName;
	}

	public void setWipName(String wipName) {
		this.wipName = wipName;
	}

	public String getWipNotes() {
		return this.wipNotes;
	}

	public void setWipNotes(String wipNotes) {
		this.wipNotes = wipNotes;
	}

	public int getWipRemains() {
		return this.wipRemains;
	}

	public void setWipRemains(int wipRemains) {
		this.wipRemains = wipRemains;
	}

	public int getWipAllowed() {
		return this.wipAllowed;
	}

	public void setWipAllowed(int wipAllowed) {
		this.wipAllowed = wipAllowed;
	}

	public short getWipIsLack() {
		return this.wipIsLack;
	}

	public void setWipIsLack(short wipIsLack) {
		this.wipIsLack = wipIsLack;
	}

	public Set<WipGet> getWipGets() {
		return this.wipGets;
	}

	public void setWipGets(Set<WipGet> wipGets) {
		this.wipGets = wipGets;
	}

	public Set<WipStockmanage> getWipStockmanages() {
		return this.wipStockmanages;
	}

	public void setWipStockmanages(Set<WipStockmanage> wipStockmanages) {
		this.wipStockmanages = wipStockmanages;
	}

	public Set<Virtualwipstore> getVirtualwipstores() {
		return this.virtualwipstores;
	}

	public void setVirtualwipstores(Set<Virtualwipstore> virtualwipstores) {
		this.virtualwipstores = virtualwipstores;
	}

	public Set<WipOts> getWipOtses() {
		return this.wipOtses;
	}

	public void setWipOtses(Set<WipOts> wipOtses) {
		this.wipOtses = wipOtses;
	}

	public Set<Wipstore> getWipstores() {
		return this.wipstores;
	}

	public void setWipstores(Set<Wipstore> wipstores) {
		this.wipstores = wipstores;
	}

	public Set<MaterialsWip> getMaterialsWips() {
		return this.materialsWips;
	}

	public void setMaterialsWips(Set<MaterialsWip> materialsWips) {
		this.materialsWips = materialsWips;
	}

}
