package com.Dao.entity;
// Generated May 7, 2017 2:26:51 AM by Hibernate Tools 3.6.0.Final

import java.util.Date;

/**
 * WipGet generated by hbm2java
 */
public class WipGet implements java.io.Serializable {

	private int wipGetId;
	private Repository repository;
	private Station station;
	private Wip wip;
	private Date stationGetWipTime;
	private int stationGetWipAmount;
	private int stationGetWipLocation;
	private Integer stationGetWipStatus;

	public WipGet() {
	}

	public WipGet(int wipGetId, Station station, Wip wip, Date stationGetWipTime, int stationGetWipAmount,
			int stationGetWipLocation) {
		this.wipGetId = wipGetId;
		this.station = station;
		this.wip = wip;
		this.stationGetWipTime = stationGetWipTime;
		this.stationGetWipAmount = stationGetWipAmount;
		this.stationGetWipLocation = stationGetWipLocation;
	}

	public WipGet(int wipGetId, Repository repository, Station station, Wip wip, Date stationGetWipTime,
			int stationGetWipAmount, int stationGetWipLocation, Integer stationGetWipStatus) {
		this.wipGetId = wipGetId;
		this.repository = repository;
		this.station = station;
		this.wip = wip;
		this.stationGetWipTime = stationGetWipTime;
		this.stationGetWipAmount = stationGetWipAmount;
		this.stationGetWipLocation = stationGetWipLocation;
		this.stationGetWipStatus = stationGetWipStatus;
	}

	public int getWipGetId() {
		return this.wipGetId;
	}

	public void setWipGetId(int wipGetId) {
		this.wipGetId = wipGetId;
	}

	public Repository getRepository() {
		return this.repository;
	}

	public void setRepository(Repository repository) {
		this.repository = repository;
	}

	public Station getStation() {
		return this.station;
	}

	public void setStation(Station station) {
		this.station = station;
	}

	public Wip getWip() {
		return this.wip;
	}

	public void setWip(Wip wip) {
		this.wip = wip;
	}

	public Date getStationGetWipTime() {
		return this.stationGetWipTime;
	}

	public void setStationGetWipTime(Date stationGetWipTime) {
		this.stationGetWipTime = stationGetWipTime;
	}

	public int getStationGetWipAmount() {
		return this.stationGetWipAmount;
	}

	public void setStationGetWipAmount(int stationGetWipAmount) {
		this.stationGetWipAmount = stationGetWipAmount;
	}

	public int getStationGetWipLocation() {
		return this.stationGetWipLocation;
	}

	public void setStationGetWipLocation(int stationGetWipLocation) {
		this.stationGetWipLocation = stationGetWipLocation;
	}

	public Integer getStationGetWipStatus() {
		return this.stationGetWipStatus;
	}

	public void setStationGetWipStatus(Integer stationGetWipStatus) {
		this.stationGetWipStatus = stationGetWipStatus;
	}

}
