package com.Dao.entity;
// Generated May 7, 2017 2:26:51 AM by Hibernate Tools 3.6.0.Final

/**
 * WipOtsId generated by hbm2java
 */
public class WipOtsId implements java.io.Serializable {

	private int wipId;
	private int otsId;

	public WipOtsId() {
	}

	public WipOtsId(int wipId, int otsId) {
		this.wipId = wipId;
		this.otsId = otsId;
	}

	public int getWipId() {
		return this.wipId;
	}

	public void setWipId(int wipId) {
		this.wipId = wipId;
	}

	public int getOtsId() {
		return this.otsId;
	}

	public void setOtsId(int otsId) {
		this.otsId = otsId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof WipOtsId))
			return false;
		WipOtsId castOther = (WipOtsId) other;

		return (this.getWipId() == castOther.getWipId()) && (this.getOtsId() == castOther.getOtsId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getWipId();
		result = 37 * result + this.getOtsId();
		return result;
	}

}
