package com.Dao.entity;
// Generated May 7, 2017 2:26:51 AM by Hibernate Tools 3.6.0.Final

/**
 * WipOts generated by hbm2java
 */
public class WipOts implements java.io.Serializable {

	private WipOtsId id;
	private Ots ots;
	private Wip wip;
	private Integer wipNum;

	public WipOts() {
	}

	public WipOts(WipOtsId id, Ots ots, Wip wip) {
		this.id = id;
		this.ots = ots;
		this.wip = wip;
	}

	public WipOts(WipOtsId id, Ots ots, Wip wip, Integer wipNum) {
		this.id = id;
		this.ots = ots;
		this.wip = wip;
		this.wipNum = wipNum;
	}

	public WipOtsId getId() {
		return this.id;
	}

	public void setId(WipOtsId id) {
		this.id = id;
	}

	public Ots getOts() {
		return this.ots;
	}

	public void setOts(Ots ots) {
		this.ots = ots;
	}

	public Wip getWip() {
		return this.wip;
	}

	public void setWip(Wip wip) {
		this.wip = wip;
	}

	public Integer getWipNum() {
		return this.wipNum;
	}

	public void setWipNum(Integer wipNum) {
		this.wipNum = wipNum;
	}

}
