package com.Dao.entity;
// Generated May 7, 2017 2:26:51 AM by Hibernate Tools 3.6.0.Final

/**
 * WipstoreId generated by hbm2java
 */
public class WipstoreId implements java.io.Serializable {

	private int wipStoreRepositoryId;
	private int wipStoreWipId;

	public WipstoreId() {
	}

	public WipstoreId(int wipStoreRepositoryId, int wipStoreWipId) {
		this.wipStoreRepositoryId = wipStoreRepositoryId;
		this.wipStoreWipId = wipStoreWipId;
	}

	public int getWipStoreRepositoryId() {
		return this.wipStoreRepositoryId;
	}

	public void setWipStoreRepositoryId(int wipStoreRepositoryId) {
		this.wipStoreRepositoryId = wipStoreRepositoryId;
	}

	public int getWipStoreWipId() {
		return this.wipStoreWipId;
	}

	public void setWipStoreWipId(int wipStoreWipId) {
		this.wipStoreWipId = wipStoreWipId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof WipstoreId))
			return false;
		WipstoreId castOther = (WipstoreId) other;

		return (this.getWipStoreRepositoryId() == castOther.getWipStoreRepositoryId())
				&& (this.getWipStoreWipId() == castOther.getWipStoreWipId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getWipStoreRepositoryId();
		result = 37 * result + this.getWipStoreWipId();
		return result;
	}

}
