package com.Dao.entity;
// Generated May 7, 2017 2:26:51 AM by Hibernate Tools 3.6.0.Final

/**
 * Wipstore generated by hbm2java
 */
public class Wipstore implements java.io.Serializable {

	private WipstoreId id;
	private Repository repository;
	private Wip wip;
	private Integer wipStoreWipNum;

	public Wipstore() {
	}

	public Wipstore(WipstoreId id) {
		this.id = id;
	}

	public Wipstore(WipstoreId id, Repository repository, Wip wip, Integer wipStoreWipNum) {
		this.id = id;
		this.repository = repository;
		this.wip = wip;
		this.wipStoreWipNum = wipStoreWipNum;
	}

	public WipstoreId getId() {
		return this.id;
	}

	public void setId(WipstoreId id) {
		this.id = id;
	}

	public Repository getRepository() {
		return this.repository;
	}

	public void setRepository(Repository repository) {
		this.repository = repository;
	}

	public Wip getWip() {
		return this.wip;
	}

	public void setWip(Wip wip) {
		this.wip = wip;
	}

	public Integer getWipStoreWipNum() {
		return this.wipStoreWipNum;
	}

	public void setWipStoreWipNum(Integer wipStoreWipNum) {
		this.wipStoreWipNum = wipStoreWipNum;
	}

}
