package com.Dao.entity;
// Generated May 7, 2017 2:26:51 AM by Hibernate Tools 3.6.0.Final

import java.util.Date;

/**
 * WipStockmanage generated by hbm2java
 */
public class WipStockmanage implements java.io.Serializable {

	private String wipStockManageId;
	private Allocation allocation;
	private Repository repository;
	private Wip wip;
	private int wipAmount;
	private int wipStockDealPersonId;
	private int wipTakePersonId;
	private int wipStockManageType;
	private Integer wipBringPersonId;
	private Date wipStockManageDate;

	public WipStockmanage() {
	}

	public WipStockmanage(String wipStockManageId, Allocation allocation, Wip wip, int wipAmount,
			int wipStockDealPersonId, int wipTakePersonId, int wipStockManageType) {
		this.wipStockManageId = wipStockManageId;
		this.allocation = allocation;
		this.wip = wip;
		this.wipAmount = wipAmount;
		this.wipStockDealPersonId = wipStockDealPersonId;
		this.wipTakePersonId = wipTakePersonId;
		this.wipStockManageType = wipStockManageType;
	}

	public WipStockmanage(String wipStockManageId, Allocation allocation, Repository repository, Wip wip, int wipAmount,
			int wipStockDealPersonId, int wipTakePersonId, int wipStockManageType, Integer wipBringPersonId,
			Date wipStockManageDate) {
		this.wipStockManageId = wipStockManageId;
		this.allocation = allocation;
		this.repository = repository;
		this.wip = wip;
		this.wipAmount = wipAmount;
		this.wipStockDealPersonId = wipStockDealPersonId;
		this.wipTakePersonId = wipTakePersonId;
		this.wipStockManageType = wipStockManageType;
		this.wipBringPersonId = wipBringPersonId;
		this.wipStockManageDate = wipStockManageDate;
	}

	public String getWipStockManageId() {
		return this.wipStockManageId;
	}

	public void setWipStockManageId(String wipStockManageId) {
		this.wipStockManageId = wipStockManageId;
	}

	public Allocation getAllocation() {
		return this.allocation;
	}

	public void setAllocation(Allocation allocation) {
		this.allocation = allocation;
	}

	public Repository getRepository() {
		return this.repository;
	}

	public void setRepository(Repository repository) {
		this.repository = repository;
	}

	public Wip getWip() {
		return this.wip;
	}

	public void setWip(Wip wip) {
		this.wip = wip;
	}

	public int getWipAmount() {
		return this.wipAmount;
	}

	public void setWipAmount(int wipAmount) {
		this.wipAmount = wipAmount;
	}

	public int getWipStockDealPersonId() {
		return this.wipStockDealPersonId;
	}

	public void setWipStockDealPersonId(int wipStockDealPersonId) {
		this.wipStockDealPersonId = wipStockDealPersonId;
	}

	public int getWipTakePersonId() {
		return this.wipTakePersonId;
	}

	public void setWipTakePersonId(int wipTakePersonId) {
		this.wipTakePersonId = wipTakePersonId;
	}

	public int getWipStockManageType() {
		return this.wipStockManageType;
	}

	public void setWipStockManageType(int wipStockManageType) {
		this.wipStockManageType = wipStockManageType;
	}

	public Integer getWipBringPersonId() {
		return this.wipBringPersonId;
	}

	public void setWipBringPersonId(Integer wipBringPersonId) {
		this.wipBringPersonId = wipBringPersonId;
	}

	public Date getWipStockManageDate() {
		return this.wipStockManageDate;
	}

	public void setWipStockManageDate(Date wipStockManageDate) {
		this.wipStockManageDate = wipStockManageDate;
	}

}
